### ISSUE TITLE
creating iksar shaman gets invalid race/class combo

### ISSUE THREAD

**Issue by erfg12** [erfg12/EQTrilogy-Old#12]
FAIL: 'name of character' has an invalid race/class combo!

Still lets you login and gets proper spells and items though...

**Comment by erfg12** [comment]
ClassRaceLookupTable was not updated to include iksar.

Also fixed some other iksar things and removed beastlord from classes.

**Comment by cursian** [comment]
Are you referring to an SQL table? I thought all of the races were hard coded?
