### ISSUE TITLE
Unable to summon corpse

### ISSUE THREAD

**Issue by jimm0thy** [erfg12/EQTrilogy-Old#19]
Non GM characters are unable to summon their corpse using the /corpse command

This is fixable by editing the Client_Process.cpp file of Zone, void Client::ProcessOP_GMSummon sub
  the code for checking if the summon target is a corpse and thus summoning it falls at the end but this comes after the player has already been kicked from the sub due to not having proper GM account status. By moving the code to the top of the sub this resolves the issue

```
void Client::ProcessOP_GMSummon(APPLAYER* pApp){
	if (pApp->size != sizeof(GMSummon_Struct)) 
	{
		cout << "Wrong size on OP_GMSummon. Got: " << pApp->size << ", Expected: " << sizeof(GMSummon_Struct) << endl;
		return;
	}
GMSummon_Struct* gms = (GMSummon_Struct*)pApp->pBuffer;
	Mob* st = entity_list.GetMob(gms->charname);
	if (st->IsCorpse()) {
		

			st->CastToCorpse()->Summon(this);
	
			return;
	}
if (admin < 100)
	{
		Message(RED, "You're not awesome enough to use this command!");
		return;
	} 

```
etc..

I'm not really great with C++ but it appears the /corpse command works now , from my testing.

**Comment by erfg12** [comment]
Added.
