### ISSUE TITLE
Equipable loot crashes zone

### ISSUE THREAD

**Issue by jimm0thy** [erfg12/EQTrilogy-Old#20]
Playing in gfay on half-elf warrior

When looting something that is also equipable (ie cloth clothes / weapons) the zone crashes stating zone client.cpp line 4080 stack around the variable 'classes' was corrupted , this also happens with races

This is fixable by increasing the size of the variable buffers on line 4040 and 4041, I simply doubled them and all appears well, though I'm sure a smaller value would be better and work

```
int16 classes[28] = {0};
int16 races[26] = {0};
```

**Comment by erfg12** [comment]
Added. You're welcome to fork the repo, add your code and send a push.
Thanks for the fix.
