### ISSUE TITLE
Kelethin lift goes up, but not down

### ISSUE THREAD

**Issue by erfg12** [erfg12/EQTrilogy-Old#7]
Kelethin lift goes up, but not down

**Comment by aceoyame** [comment]
Talk to me, in one of the sources we have for this that bug was fixed. I want to start working on this again and have the domain

**Comment by erfg12** [comment]
If you click enough times on the lift to go down you just die and disconnect from the server.

**Comment by erfg12** [comment]
Added a boolean to client called "elevator". In the code for buttons I made a toggle for open/close. Now we can change it on the fly.
